providers = ["python"]

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run CSV_cleaner_V3.py --server.port=8080 --server.address=0.0.0.0"
